import streamlit as st
from PIL import Image
def display(tab):
   tab.header("Abstract")
   tab.write("In the field of polymer informatics, the availability of high-quality structured data for training machine learning models to predict polymer properties is a crucial problem.  Transferring knowledge from the data-rich molecule domain to polymers using deep neural networks is a promising avenue for overcoming this data scarcity.  In this study, we utilise different transfer learning techniques such as zero-shot learning, few-shot learning, fine-tuning, and frozen featurization to improve the prediction accuracy of the polymer band gap that determines the material's electrical conductivity and optical properties.")
   tab.write("We develop base machine learning models for molecules and polymers using three different fingerprinting techniques that numerically encode the polymers structure, namely Circular, PolyBERT, and MiniLM fingerprints. The Circular fingerprints consist of a vector made of manually selected features, the PolyBERT fingerprints are obtained using the transformer trained using polymer data where as the MiniLM fingerprints are obtained using sentence-transformers. The models for molecules serve as a starting point for training the transfer learning models, while the base models for polymers allow us to validate the performance improvements of our transfer learning approaches. We find that zero-shot and few-shot learning from molecules to polymers does not improve the prediction accuracy for the band gap, because the difference between molecules and polymers cannot be learned in zero or few epochs using the chosen ML architecture. On the contrary, the fine-tuning and frozen featurization transfer learning models show significant improvements in the prediction accuracy of the band gap. We conclude that retaining a few layers in frozen featurization or fine-tuning allows for learning the differences as well as similarities between the molecule and polymer domains.")
   tab.header("Our Results")

   results = Image.open("results.png")
   st.image(results, caption=" Comparison between r2 score of transfer learning techniques and base polymer models")